### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by ElioEfra99** [ByneappLLC/flutter_config#25]
I am having the following error when executing an app with "flutter_config" in iOS, it actually runs perfectly with my Android device.

I already did some research but found nothing about this error, I also tried several things, such as:

* flutter clean
* update cocoapods.
* remove podfile.lock
* pod update
* pod install
* packages upgrade
* flutter upgrade

As nothing of this worked, I decided to post it here.

As stated in the documentation no further configuration is needed for iOS, so I didn't change anything in the first place, but then I went to Xcode and applied the recommended settings because it was not being able to execute the app. 

After that, this is what I got, btw It is a very long error log and actually looks something like this:
![Screen Shot 2020-11-07 at 17 19 51](https://user-images.githubusercontent.com/41178114/98453322-7a075080-211d-11eb-95da-ac50e37aef82.png)

There are a lot of export statements after this, but the end of the error log is something like this:

![Screen Shot 2020-11-07 at 17 20 28](https://user-images.githubusercontent.com/41178114/98453333-93100180-211d-11eb-9696-8f4647abd09a.png)

There's a line stating that a nil conversion into String happened

![Screen Shot 2020-11-07 at 17 22 18](https://user-images.githubusercontent.com/41178114/98453360-d10d2580-211d-11eb-80d7-b7fc323b84cd.png)

This is the error log in Visual Studio Code:

![Screen Shot 2020-11-07 at 17 29 20](https://user-images.githubusercontent.com/41178114/98453750-424ed780-2122-11eb-9518-f94b4a9c7883.png)

Can someone tell if this is a package error or did I just made something wrong?

Thank you in advance.

**Comment by phil-flyclops** [comment]
I'm getting the exact same error and trying to work through it

**Comment by phil-flyclops** [comment]
Ah, the problem is the .rb script isn't looking for files called .env, it is looking for .envfile.  If no .envfile is found, it doesn't fall back to .env

**Comment by phil-flyclops** [comment]
I created this to fix the issue, can apply locally to temporarily get over

**Comment by lordvcs** [comment]
I have the same issue too

**Comment by lordvcs** [comment]
> I created this to fix the issue, can apply locally to temporarily get over #27

How do I temporarly apply this?

**Comment by edTheGuy00** [comment]
Can you confirm this was fixed with Version 1.0.8?

**Comment by lordvcs** [comment]
@edTheGuy00 this issue seems to be fixed on the new version, but I still cant get it to work with ios
This is my AppDelegate.swift file
![image](https://user-images.githubusercontent.com/6374881/103125780-3a3aff00-46b2-11eb-8032-f427aa1c2cf3.png)
and this is the console output 
![image](https://user-images.githubusercontent.com/6374881/103125818-5dfe4500-46b2-11eb-9dc3-1f26082b36b1.png)

Am I doing something wrong?

BTW thanks for the plugin, works fine on android

**Comment by nehamallama** [comment]
RUN AWAY! They dont update anything or respond to any open issues. Use this dep instead https://pub.dev/packages/flutter_dotenv

**Comment by edTheGuy00** [comment]
So this issue was fixed since `1.0.8` . I'm going to go ahead and close this issue. @lordvcs If you are still encountering other unrelated problems, can you open a separate issue? 

@nehamallama Oh hey again, you must passionately hate this library as you are commenting the same thing on every issue. Could you at least remove this from your Github repositories? https://github.com/nehamallama/flutter_config
